#!/bin/sh
#
# $OpenBSD: zabbix_proxy.rc,v 1.5 2014/04/09 06:27:56 robert Exp $

daemon="/usr/local/sbin/zabbix_proxy"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_pre() {
	install -d -o _zabbix -g _zabbix /var/run/zabbix
}

rc_cmd $1
